import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { LayoutComponent } from './layout.component';
const routes: Routes = [
{
	path: '',
	component: LayoutComponent,
	children: [
	
	{ path: '', redirectTo: 'dashboard', pathMatch: 'prefix' },
	{ path: 'dashboard', loadChildren: () => import('./dashboard/dashboard.module').then(m => m.DashboardModule) },
	{ path: 'master-equipment', loadChildren: () => import('./admin-master/equipment-master/equipment-master.module').then(m => m.EquipmentMasterModule) },
	{ path: 'master-ethinicity', loadChildren: () => import('./admin-master/ethinicity-master/ethinicity-master.module').then(m => m.EthinicityMasterModule) },
	{ path: 'master-instrumentation', loadChildren: () => import('./admin-master/instrumentation-master/instrumentation-master.module').then(m => m.InstrumentationMasterModule) },
	{ path: 'master-language', loadChildren: () => import('./admin-master/language-master/language-master.module').then(m => m.LanguageMasterModule) },
	{ path: 'master-nationality', loadChildren: () => import('./admin-master/nationality-master/nationality-master.module').then(m => m.NationalityMasterModule) },
	{ path: 'master-physician', loadChildren: () => import('./admin-master/physician-master/physician-master.module').then(m => m.PhysicianMasterModule) },
	{ path: 'master-race', loadChildren: () => import('./admin-master/race-master/race-master.module').then(m => m.RaceMasterModule) },
	{ path: 'master-religion', loadChildren: () => import('./admin-master/religion-master/religion-master.module').then(m => m.ReligionMasterModule) },
	{ path: 'master-surgery', loadChildren: () => import('./admin-master/surgery-master/surgery-master.module').then(m => m.SurgeryMasterModule) },
	{ path: 'master-user/:slug', loadChildren: () => import('./admin-master/user-master/user-master.module').then(m => m.UserMasterModule) },
	{ path: 'master-incident', loadChildren: () => import('./admin-master/incident-master/incident-master.module').then(m => m.IncidentMasterModule) },
	{ path: 'master-supplies', loadChildren: () => import('./admin-master/supplies-master/supplies-master.module').then(m => m.SuppliesMasterModule) },
	{ path: 'master-anesthesia', loadChildren: () => import('./admin-master/master-anesthesia/master-anesthesia.module').then(m => m.MasterAnesthesiaModule) },
	{ path: 'master-relationship', loadChildren: () => import('./admin-master/master-relationship/master-relationship.module').then(m => m.MasterRelationshipModule) },
	{ path: 'master-block', loadChildren: () =>import('./admin-master/master-block/master-block.module').then(m => m.MasterBlockModule) },
	{ path: 'master-icd-code', loadChildren: () =>import('./admin-master/master-icd10/master-icd10.module').then(m => m.MasterIcd10Module) },
	{ path: 'master-procedure', loadChildren: () =>import('./admin-master/master-procedure/master-procedure.module').then(m => m.MasterProcedureModule) },
	{ path: 'master-cpt', loadChildren: () =>import('./admin-master/master-cpt/master-cpt.module').then(m => m.MasterCptModule) },
	{ path: 'surgery-center-settings/:id', loadChildren: () =>import('./admin-master/surgery-center-settings/surgery-center-settings.module').then(m => m.SurgeryCenterSettingsModule) },
	{ path: 'surgery-contact-settings/:id', loadChildren: () =>import('./admin-master/surgery-contact-settings/surgery-contact-settings.module').then(m => m.SurgeryContactSettingsModule) },
	{ path: 'physician-center-settings/:id', loadChildren: () =>import('./admin-master/physician-center-settings/physician-center-settings.module').then(m => m.PhysicianCenterSettingsModule) },
	{ path: 'physician-contact-settings/:id', loadChildren: () =>import('./admin-master/physician-contact-settings/physician-contact-settings.module').then(m => m.PhysicianContactSettingsModule) },
	{ path: 'user-permission/:slug', loadChildren: () =>import('./admin-master/user-permission/user-permission.module').then(m => m.UserPermissionModule) },
	{ path: 'master-specility', loadChildren: () =>import('./admin-master/master-specility/master-specility.module').then(m => m.MasterSpecilityModule) },
	{ path: 'master-designation', loadChildren: () =>import('./admin-master/master-designation/master-designation.module').then(m => m.MasterDesignationModule) },
	{ path: 'master-forms', loadChildren: () =>import('./admin-master/master-forms/master-forms.module').then(m => m.MasterFormsModule) },
	{ path: 'master-alerts', loadChildren: () =>import('./admin-master/master-alerts/master-alerts.module').then(m => m.MasterAlertsModule) },
	{ path: 'languages', loadChildren: () => import('./languages/languages.module').then(m => m.LanguagesModule) },
	{ path: 'form-builder/:slug', loadChildren: () => import('./form-editior/form-editior.module').then(m => m.FormEditiorModule) },
	{ path: 'patient-list', loadChildren: () => import('./patient-list/patient-list.module').then(m => m.PatientListModule) },
	{ path: 'add-patient', loadChildren: () => import('./add-patient/add-patient.module').then(m => m.AddPatientModule) },
	{ path: 'appointment-list', loadChildren: () => import('./appointment-list/appointment-list.module').then(m => m.AppointmentListModule) },
	{ path: 'edit-patient/:id', loadChildren: () => import('./edit-patient/edit-patient.module').then(m => m.EditPatientModule) },
	{ path: 'language-phrase/:id', loadChildren: () => import('./language-phrase/language-phrase.module').then(m => m.LanguagePhraseModule) },
	{ path: 'medical-form', loadChildren: () => import('./medical-form/medical-form.module').then(m => m.MedicalFormModule) },
	{ path: 'legal-form', loadChildren: () => import('./legal-form/legal-form.module').then(m => m.LegalFormModule) },
	{ path: 'chat', loadChildren: () => import('./chat/chat.module').then(m => m.ChatModule) },
	{ path: 'view-appointment/:id/:pID', loadChildren: () => import('./view-appointment/view-appointment.module').then(m => m.ViewAppointmentModule) },
	{ path: 'edit-surgery-center/:id', loadChildren: () =>import('./admin-master/edit-surgery-center/edit-surgery-center.module').then(m => m.EditSurgeryCenterModule) },
	{ path: 'edit-physician-office/:id', loadChildren: () =>import('./admin-master/edit-physician-office/edit-physician-office.module').then(m => m.EditPhysicianOfficeModule) },
	{ path: 'surgery-forms/:id', loadChildren: () => import('./surgery-forms/surgery-forms.module').then(m => m.SurgeryFormsModule) },
	{ path: 'edit-appointment/:id/:pID', loadChildren: () => import('./edit-appointment/edit-appointment.module').then(m => m.EditAppointmentModule) },
	{ path: 'add-attachments/:id', loadChildren: () => import('./add-attachments/add-attachments.module').then(m => m.AddAttachmentsModule) },
	{ path: 'notifications', loadChildren: () =>import('./communication/notifications/notifications.module').then(m => m.NotificationsModule) },
	{ path: 'add-notifications', loadChildren: () =>import('./communication/add-notifications/add-notifications.module').then(m => m.AddNotificationsModule) },
	{ path: 'notification-action', loadChildren: () =>import('./communication/notification-action/notification-action.module').then(m => m.NotificationActionModule) },	
	{ path: 'add-notification-type', loadChildren: () => import('./communication/add-notification-type/add-notification-type.module').then(m => m.AddNotificationTypeModule) },
	{ path: 'edit-notification/:id', loadChildren: () => import('./communication/edit-notification/edit-notification.module').then(m => m.EditNotificationModule) },
	{ path: 'kb-articles', loadChildren: () =>import('./admin-master/articles/articles.module').then(m => m.ArticlesModule) },
	{ path: 'knowledge-base', loadChildren: () =>import('./knowledge-base/knowledge-base/knowledge-base.module').then(m => m.KnowledgeBaseModule) },
	{ path: 'kb-category', loadChildren: () =>import('./admin-master/kb-category/kb-category.module').then(m => m.KbCategoryModule) },
	{ path: 'kb-article-feedback', loadChildren: () =>import('./admin-master/kb-article-feedback/kb-article-feedback.module').then(m => m.KbArticleFeedbackModule) },
	{ path: 'document-category', loadChildren: () =>import('./admin-master/document-category/document-category.module').then(m => m.DocumentCategoryModule) },
	{ path: 'actions-notifications/:id', loadChildren: () => import('./communication/actions-notifications/actions-notifications.module').then(m => m.ActionsnotificationsModule) },
	{ path: 'update-notifications/:id', loadChildren: () => import('./communication/update-notifications/update-notifications.module').then(m => m.UpdatenotificationsModule) },
	{ path: 'kb-reference/:id', loadChildren: () => import('./knowledge-base/kb-reference/kb-reference.module').then(m => m.KbReferenceModule) },
	{ path: 'kb-attachment/:id', loadChildren: () => import('./knowledge-base/kb-attachment/kb-attachment.module').then(m => m.KbAttachmentModule) },
	{ path: 'assign-notification/:id', loadChildren: () => import('./communication/assign-notification/assign-notification.module').then(m => m.AssignNotificationModule) },
	{ path: 'assign-notification-list/:id', loadChildren: () => import('./communication/assign-notification-list/assign-notification-list.module').then(m => m.AssignNotificationListModule) },
	{ path: 'appointment-history', loadChildren: () => import('./appointment-history/appointment-history.module').then(m => m.AppointmentHistoryModule) },
	{ path: 'system-email', loadChildren: () => import('./Email/system-email/system-email.module').then(m => m.SystemEmailModule) },
	{ path: 'email-templete', loadChildren: () => import('./Email/email-templete/email-templete.module').then(m => m.EmailTempleteModule) },
	{ path: 'walking', loadChildren: () => import('./walking/walking.module').then(m => m.WalkingModule) },
	{ path: 'quik-book', loadChildren: () => import('./quik-book/quik-book.module').then(m => m.QuikBookModule) },
	{ path: 'quick-booking-list', loadChildren: () => import('./quick-booking-list/quick-booking-list.module').then(m => m.QuickBookingListModule) },
	{ path: 'walkin-list', loadChildren: () => import('./walkin-list/walkin-list.module').then(m => m.WalkinListModule) },	
	{ path: 'vc-history', loadChildren: () => import('./virtual-consultation/vc-history/vc-history.module').then(m => m.VcHistoryModule) },
	{ path: 'vc-list', loadChildren: () => import('./virtual-consultation/vc-list/vc-list.module').then(m => m.VcListModule) },
	{ path: 'vc-view/:id', loadChildren: () => import('./virtual-consultation/vc-view/vc-view.module').then(m => m.VcViewModule) },
	{ path: 'vc-edit/:id', loadChildren: () => import('./virtual-consultation/vc-edit/vc-edit.module').then(m => m.VcEditModule) },
	{ path: 'upload-doc/:id', loadChildren: () => import('./virtual-consultation/upload-doc/upload-doc.module').then(m => m.UploadDocModule) },
	{ path: 'vc-notification/:id', loadChildren: () => import('./virtual-consultation/vc-notification/vc-notification.module').then(m => m.VcNotificationModule) },

	{ path: 'intake', loadChildren: () =>import('./patient-intake/intake/intake.module').then(m => m.IntakeModule) },
	{ path: 'add-intake', loadChildren: () =>import('./patient-intake/add-intake/add-intake.module').then(m => m.AddIntakeModule) },
	{ path: 'intake-action', loadChildren: () =>import('./patient-intake/intake-action/intake-action.module').then(m => m.IntakeActionModule) },	
	{ path: 'add-intake-type', loadChildren: () => import('./patient-intake/add-intake-type/add-intake-type.module').then(m => m.AddIntakeTypeModule) },
	{ path: 'edit-intake/:id', loadChildren: () => import('./patient-intake/edit-intake/edit-intake.module').then(m => m.EditIntakeModule) },
	{ path: 'assign-intake/:id', loadChildren: () => import('./patient-intake/assign-intake/assign-intake.module').then(m => m.AssignIntakeModule) },
	{ path: 'assign-intake-list/:id', loadChildren: () => import('./patient-intake/assign-intake-list/assign-intake-list.module').then(m => m.AssignIntakeListModule) },
	{ path: 'update-intake/:id', loadChildren: () => import('./patient-intake/update-intake/update-intake.module').then(m => m.UpdateIntakeModule) },
	{ path: 'actions-intake/:id', loadChildren: () => import('./patient-intake/actions-intake/actions-intake.module').then(m => m.ActionsIntakeModule) },
	{ path: 'change-password', loadChildren: () => import('./change-password/change-password.module').then(m => m.ChangePasswordModule) },
	{ path: 'video-chat/:id/:name', loadChildren: () => import('./video-chat/video-chat.module').then(m => m.VideoChatModule) },
	{ path: 'view-form-data/:bookId/:formId', loadChildren: () => import('./view-form-data/view-form-data.module').then(m => m.ViewFormDataModule) },


	// patient-section
	{ path: 'appointment-booking', loadChildren: () => import('./patient-section/appointment-booking/appointment-booking.module').then(m => m.AppointmentBookingModule) },
	{ path: 'edit-patients/:id/:bookID', loadChildren: () => import('./patient-section/edit-patients/edit-patients.module').then(m => m.EditPatientsModule) },
	{ path: 'patient-dashboard', loadChildren: () => import('./patient-section/patient-dashboard/patient-dashboard.module').then(m => m.PatientDashboardModule) },
	{ path: 'reset-password', loadChildren: () => import('./patient-section/reset-password/reset-password.module').then(m => m.ResetPasswordModule) },
	{ path: 'patient-vc-history', loadChildren: () => import('./patient-section/virtual-consultation/vc-history/vc-history.module').then(m => m.VcHistoryModule) },
	{ path: 'patient-vc-list', loadChildren: () => import('./patient-section/virtual-consultation/vc-list/vc-list.module').then(m => m.VcListModule) },
	{ path: 'patient-vc-view/:id', loadChildren: () => import('./patient-section/virtual-consultation/vc-view/vc-view.module').then(m => m.VcViewModule) },
	{ path: 'booking-history', loadChildren: () => import('./patient-section/appointment-history/appointment-history.module').then(m => m.AppointmentHistoryModule) },
	{ path: 'booking-list', loadChildren: () => import('./patient-section/appointment-list/appointment-list.module').then(m => m.AppointmentListModule) },
	{ path: 'edit-user/:id', loadChildren: () => import('./patient-section/edit-user/edit-user.module').then(m => m.EditUserModule) },
	{ path: 'vc-cancel-list', loadChildren: () => import('./patient-section/virtual-consultation/vc-cancel-list/vc-cancel-list.module').then(m => m.VcCancelListModule) },
	{ path: 'patient-vc-edit/:id', loadChildren: () => import('./patient-section/virtual-consultation/vc-edit/vc-edit.module').then(m => m.VcEditModule) },
	{ path: 'user-video-chat/:id', loadChildren: () => import('./patient-section/user-video-chat/user-video-chat.module').then(m => m.UserVideoChatModule) },
	]
}
];



@NgModule({
	imports: [RouterModule.forChild(routes)],
	exports: [RouterModule]
})
export class LayoutRoutingModule { }
